#!/usr/bin/env python3
"""Kolmogorov measurement-operator matrix -> tab_operator_body.tex.

Reads the operator runs by their PROTOCOL STAMP, never by filename. A run
corrupted by an operator is stamped kolm2d_matched_v1_op_<tag>; the clean row
is kolm2d_matched_v1. Filenames are a hint (the same glob matches override and
operator runs alike) and have already caused two silent mix-ups this campaign,
so the stamp inside the payload is the only thing trusted here.

K MATTERS. DMF-Gen has clean evaluations at K = 8/16/32/64 and every operator
run is K=8, so taking "the clean DMF-Gen file" without filtering silently
compares K=64 against K=8 and understates the operator penalty. Deterministic
rows are K=1 throughout. The loader therefore pins K to 8 for generative rows
and 1 for deterministic ones, and refuses to emit a row whose clean and
corrupted entries disagree on K.

Usage: python make_operator_table.py [--tex out.tex] [--json out.json]
"""
import argparse
import glob
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STM = ROOT / "Save_TrainedModel" / "kolmogorov2d"
DENSITY = 655                       # the canonical 1% row
OPS = ["clean", "noise0.1", "noise0.3", "occl0.25"]
OP_HEAD = {"clean": "clean", "noise0.1": r"$\sigma{=}0.1$",
           "noise0.3": r"$\sigma{=}0.3$", "occl0.25": r"25\% slab"}
DET = {"senseiver", "mlprbf", "geofno"}     # K=1 rows
ROWS = [("geofno", "Geo-FNO"), ("dmfgen", r"\dmfgen{}"), ("sit", "SiT"),
        ("s3gm", "S3GM (PC-DPS)"), ("latentfm", "Latent FM"),
        ("mlprbf", "MLP-RBF"), ("senseiver", "Senseiver")]
FAM = {"dmfgen": "pointcloud_ffm", "senseiver": "baseline_det",
       "mlprbf": "baseline_mlp_rbf", "geofno": "baseline_geofno",
       "sit": "baseline_sit", "s3gm": "baseline_s3gm",
       "latentfm": "baseline_latent_fm"}


def load():
    out = {}
    for m, fam in FAM.items():
        want_K = 1 if m in DET else 8
        base = STM.parent / "kolmogorov2d_fullbudget" if m == "geofno" else STM   # reported row, see fleet_select.ROW_SOURCE
        for p in glob.glob(str(base / fam / "*" / "Evaluation" / "kolm_fleet*.json")):
            try:
                d = json.load(open(p))
            except Exception:
                continue
            pr = d.get("protocol", "")
            if pr == "kolm2d_matched_v1":
                op = "clean"
            elif pr.startswith("kolm2d_matched_v1_op_"):
                op = pr.split("_op_", 1)[1]
            else:
                continue
            n = d.get("n_obs")
            if not (isinstance(n, list) and n and int(n[0]) == DENSITY):
                continue
            if int(d.get("K", -1)) != want_K:
                continue
            a = d["summary"]["aggregate"]
            out.setdefault(m, {})[op] = (a["rel_l2_mean"], a["crps"])
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tex", default=str(ROOT / "Paper/pof2026/tab_operator_body.tex"))
    ap.add_argument("--json", default=None)
    a = ap.parse_args()
    tab = load()

    print(f"{'method':<14}" + "".join(f"{OPS[i]:>10}" for i in range(len(OPS)))
          + f"{'occl/clean':>12}")
    lines = ["% GENERATED by src/figs_pof/make_operator_table.py -- do not hand-edit"]
    missing = []
    for m, label in ROWS:
        r = tab.get(m, {})
        if "clean" not in r:
            missing.append(m)
            continue
        cells = []
        for op in OPS:
            cells.append(f"{r[op][0]:.3f}" if op in r else "---")
            if op not in r:
                missing.append(f"{m}/{op}")
        ratio = (f"{r['occl0.25'][0] / r['clean'][0]:.2f}"
                 if "occl0.25" in r else "---")
        lines.append(f"{label} & " + " & ".join(cells) + f" & {ratio} \\\\")
        print(f"{m:<14}" + "".join(f"{c:>10}" for c in cells) + f"{ratio:>12}")
    Path(a.tex).write_text("\n".join(lines) + "\n")
    print(f"\nwrote {a.tex}")
    if missing:
        print("INCOMPLETE -- still missing: " + ", ".join(missing))
        print("(re-run this script when those jobs land; the table is a "
              "one-command refresh)")
    if a.json:
        Path(a.json).write_text(json.dumps(tab, indent=1))


if __name__ == "__main__":
    main()
