#!/usr/bin/env python3
"""Emit the LaTeX row bodies of tab:kolm and tab:cyl straight from the canonical
eval JSONs, so the paper's 2D numbers are machine-derived and re-derivable.

Writes (Paper/pof2026/):
    tab_kolm_body.tex   rows for tab:kolm   (single-channel: vorticity)
    tab_cyl_body.tex    rows for tab:cyl    (per-channel Ux / Uy / p, p unobserved)
    tab_2d_numbers.json every number used, for the prose \\todo fills

Sources, all under Save_TrainedModel/<ds>/:
    <family>/<run>/Evaluation/{kolm,cyl}_fleet_<model>_K*.json   (n=50, K=8 / K=1)
    baseline_classical/classical_baselines_main_*.json           (all held-out frames)

Conventions kept from the eval driver: deterministic rows carry K=1 and NULL
dispersion (CRPS == MAE exactly), so their Cov.90 cell prints "---"; the best
value in each accuracy column is bolded; cost columns are the run's own
recorded GPU (all canonical 2D rows: H100).
"""
import glob
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STM = ROOT / "Save_TrainedModel"
OUT = ROOT / "Paper" / "pof2026"

NICE = {"dmfgen": r"\dmfgen{} (NFE 4)", "sit": "SiT (50 steps)",
        "latentfm": "Latent FM (NFE 4)", "senseiver": "Senseiver",
        "mlprbf": "MLP-RBF", "geofno": "Geo-FNO", "s3gm": "S3GM (PC-DPS)"}
ORDER = ["dmfgen", "sit", "latentfm", "s3gm", "senseiver", "mlprbf", "geofno"]


def fleet(ds):
    """model -> canonical payload, chosen by payload identity (fleet_select.py),
    never by filename -- a glob here once pulled occlusion runs into tab:kolm."""
    import sys
    sys.path.insert(0, str(ROOT / "src"))
    from fleet_select import load_canonical_fleet
    return load_canonical_fleet(ds, STM)


def classical(ds):
    rows = {}
    for f in sorted(glob.glob(str(STM / ds / "baseline_classical" / "classical_baselines_main_*.json"))):
        tag = Path(f).stem
        for k, v in json.load(open(f)).get("results", {}).items():
            if isinstance(v, dict) and "aggregate" in v:
                rows[f"{k}|{tag}"] = v
    return rows


def b(x, best, n=3):
    """format, bolding the column optimum"""
    s = f"{x:.{n}f}"
    return rf"\textbf{{{s}}}" if abs(x - best) < 1e-12 else s


def kolm_table():
    ds = "kolmogorov2d"
    F, C = fleet(ds), classical(ds)
    learned = [(m, F[m]) for m in ORDER if m in F]
    l2 = [d["summary"]["aggregate"]["rel_l2_mean"] for _, d in learned]
    cr = [d["summary"]["aggregate"]["crps"] for _, d in learned]
    cls = []
    for key, v in C.items():
        name, tag = key.split("|")
        if name.startswith("constant_test"):
            continue
        per = "periodic" in tag and "nonperiodic" not in tag
        label = {"kdtree": "Nearest neighbour", "idw": r"IDW ($k{=}8$)",
                 "gappy_pod": r"Gappy POD ($r{=}80$)",
                 "constant_train_mean": "Training mean"}.get(name.split("_n")[0], name)
        if name.startswith(("kdtree", "idw")):
            label += " (per.)" if per else " (non-per.)"
        elif per:
            continue                      # POD / mean are identical in both files
        cls.append((label, v["aggregate"]))
    all_l2 = l2 + [a["rel_l2_mean"] for _, a in cls]
    all_cr = cr + [a["crps"] for _, a in cls]
    bl2, bcr = min(all_l2), min(all_cr)
    # single-sample rel-L2 (what one posterior draw scores; the gallery number).
    # Deterministic and classical rows have one prediction, so sample == mean.
    sm = [d["summary"]["aggregate"].get("rel_l2_single",
                                        d["summary"]["aggregate"]["rel_l2_mean"])
          for _, d in learned]
    bsm = min(sm + [a["rel_l2_mean"] for _, a in cls])

    lines = []
    for m, d in learned:
        a = d["summary"]["aggregate"]
        cov = a.get("coverage_90")
        smp = a.get("rel_l2_single", a["rel_l2_mean"])
        lines.append(f"{NICE[m]} & {b(a['rel_l2_mean'], bl2)} & {b(smp, bsm)} & {b(a['crps'], bcr)} & "
                     f"{'---' if cov is None else f'{cov:.2f}'} & "
                     f"{d['inference_seconds_per_field_mean']:.2f} & "
                     f"{d['inference_peak_gpu_gb']:.2f} \\\\")
    lines.append(r"\hline")
    for label, a in sorted(cls, key=lambda r: r[1]["rel_l2_mean"]):
        lines.append(f"{label} & {b(a['rel_l2_mean'], bl2)} & {b(a['rel_l2_mean'], bsm)} & {b(a['crps'], bcr)} & --- & --- & --- \\\\")
    (OUT / "tab_kolm_body.tex").write_text(
        "% GENERATED by src/figs_pof/make_2d_tables.py -- do not hand-edit\n" + "\n".join(lines) + "\n")
    return {m: d["summary"]["aggregate"] for m, d in learned}, {l: a for l, a in cls}


def cyl_table():
    ds = "cylinder2d"
    F, C = fleet(ds), classical(ds)
    learned = [(m, F[m]) for m in ORDER if m in F]
    fields = learned[0][1]["field_names"]
    l2 = [d["summary"]["aggregate"]["rel_l2_mean"] for _, d in learned]
    cls = []
    for key, v in C.items():
        name, tag = key.split("|")
        if name.startswith("constant_test"):
            continue
        base = name.split("_n")[0]
        label = {"kdtree": "Nearest neighbour", "idw": r"IDW ($k{=}8$)",
                 "constant_train_mean": "Training mean"}.get(base)
        if base == "gappy_pod":
            label = r"Gappy POD ($r{=}20$)" if "pod20" in tag else r"Gappy POD ($r{=}80$)"
        if label is None or any(label == c[0] for c in cls):
            continue
        cls.append((label, v))
    bl2 = min(l2 + [v["aggregate"]["rel_l2_mean"] for _, v in cls])
    bp = min([d["summary"]["per_field"]["p"]["rel_l2_mean"] for _, d in learned]
             + [v["per_field"]["p"]["rel_l2_mean"] for _, v in cls])

    lines = []
    for m, d in learned:
        a, pf = d["summary"]["aggregate"], d["summary"]["per_field"]
        cov = a.get("coverage_90")
        lines.append(f"{NICE[m]} & {b(a['rel_l2_mean'], bl2)} & "
                     + " & ".join(f"{pf[f]['rel_l2_mean']:.3f}" if f != "p"
                                  else b(pf[f]["rel_l2_mean"], bp) for f in fields)
                     + f" & {a['crps']:.3f} & {'---' if cov is None else f'{cov:.2f}'} & "
                       f"{d['inference_seconds_per_field_mean']:.2f} \\\\")
    lines.append(r"\hline")
    for label, v in sorted(cls, key=lambda r: r[1]["aggregate"]["rel_l2_mean"]):
        a, pf = v["aggregate"], v["per_field"]
        lines.append(f"{label} & {b(a['rel_l2_mean'], bl2)} & "
                     + " & ".join(f"{pf[f]['rel_l2_mean']:.3f}" if f != "p"
                                  else b(pf[f]["rel_l2_mean"], bp) for f in fields)
                     + f" & {a['crps']:.3f} & --- & --- \\\\")
    (OUT / "tab_cyl_body.tex").write_text(
        "% GENERATED by src/figs_pof/make_2d_tables.py -- do not hand-edit\n" + "\n".join(lines) + "\n")
    return ({m: (d["summary"]["aggregate"], d["summary"]["per_field"]) for m, d in learned},
            {l: v for l, v in cls})


if __name__ == "__main__":
    k_l, k_c = kolm_table()
    c_l, c_c = cyl_table()
    dump = {
        "kolmogorov2d": {"learned": {m: {"rel_l2": a["rel_l2_mean"], "crps": a["crps"],
                                         "cov90": a.get("coverage_90"),
                                         "spread_error": a.get("spread_error_ratio")}
                                     for m, a in k_l.items()},
                         "classical": {l: {"rel_l2": a["rel_l2_mean"], "crps": a["crps"]}
                                       for l, a in k_c.items()}},
        "cylinder2d": {"learned": {m: {"rel_l2": a["rel_l2_mean"], "crps": a["crps"],
                                       "cov90": a.get("coverage_90"),
                                       "spread_error": a.get("spread_error_ratio"),
                                       "per_field": {f: pf[f]["rel_l2_mean"] for f in pf}}
                                   for m, (a, pf) in c_l.items()},
                       "classical": {l: {"rel_l2": v["aggregate"]["rel_l2_mean"],
                                         "crps": v["aggregate"]["crps"],
                                         "per_field": {f: v["per_field"][f]["rel_l2_mean"]
                                                       for f in v["per_field"]}}
                                     for l, v in c_c.items()}},
    }
    (OUT / "tab_2d_numbers.json").write_text(json.dumps(dump, indent=1))
    for f in ("tab_kolm_body.tex", "tab_cyl_body.tex", "tab_2d_numbers.json"):
        print("wrote", OUT / f)
    print("\n--- tab_kolm_body.tex ---\n" + (OUT / "tab_kolm_body.tex").read_text())
    print("--- tab_cyl_body.tex ---\n" + (OUT / "tab_cyl_body.tex").read_text())
