#!/usr/bin/env python3
"""Emit the LaTeX row body of the surface-to-field table from the eval JSONs.

Source: Save_TrainedModel/cylinder2d_surface/*/*/Evaluation/cyl_surface_*.json
(learned, n=50 Re-stratified held-out frames) and baseline_classical/*.json
(all 600 frames). Columns are tap budgets per field on the 360-cell wall ring.

Grid-locked models (geofno, sit, latent_fm, s3gm) draw from the 62 unique grid
cells the ring rasterizes onto, so their 128 and 360 entries are identical to
64 BY CONSTRUCTION; where the eval was not re-run at those budgets we print the
64-tap value with a dagger rather than leaving a hole or implying new work.
"""
import glob, json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STM = ROOT / "Save_TrainedModel" / "cylinder2d_surface"
OUT = ROOT / "Paper" / "pof2026"
TAPS = [32, 64, 128, 360]
GRID = {"geofno", "sit", "latent_fm", "s3gm"}          # pool caps at 62 cells
NICE = {"senseiver": "Senseiver", "geofno": "Geo-FNO", "dmfgen": r"\dmfgen{}",
        "mlp_rbf": "MLP-RBF", "sit": "SiT", "latent_fm": "Latent FM", "s3gm": "S3GM"}
ORDER = ["senseiver", "geofno", "dmfgen", "mlp_rbf", "sit", "latent_fm", "s3gm"]


def learned():
    out = {}
    for p in glob.glob(str(STM / "*" / "*" / "Evaluation" / "cyl_surface_*.json")):
        d = json.load(open(p))
        # the combined sweep payload (cyl_surface_<m>_sweep.json) carries
        # rel_l2_by_n instead of a single n_obs; the per-density files are the
        # ones with a summary, so skip anything without both keys
        if "n_obs" not in d or "summary" not in d:
            continue
        m, n = d["model"], int(d["n_obs"][0])
        out.setdefault(m, {})[n] = (d["summary"]["aggregate"]["rel_l2_mean"],
                                    d["summary"]["aggregate"]["crps"])
    return out


def classical():
    out = {}
    for f in glob.glob(str(STM / "baseline_classical" / "*.json")):
        tag = Path(f).stem
        for k, v in json.load(open(f)).get("results", {}).items():
            if "aggregate" not in v:
                continue
            if "_n" not in k:          # e.g. constant_train_mean: no tap budget
                continue
            base, n = k.rsplit("_n", 1)
            if not n.isdigit():
                continue
            lbl = {"idw": r"IDW ($k{=}8$)", "kdtree": "Nearest neighbor"}.get(base)
            if base == "gappy_pod":
                lbl = r"Gappy POD ($r{=}20$)" if "pod20" in tag else r"Gappy POD ($r{=}80$)"
            if lbl is None:
                continue
            out.setdefault(lbl, {})[int(n)] = (v["aggregate"]["rel_l2_mean"], v["aggregate"]["crps"])
    return out


def fmt(vals, m=None):
    cells = []
    for t in TAPS:
        if t in vals:
            cells.append(f"{vals[t][0]:.3f}")
        elif m in GRID and 64 in vals and t > 64:
            cells.append(rf"{vals[64][0]:.3f}$^\dagger$")   # pool-capped, identical by construction
        else:
            cells.append("---")
    return cells


if __name__ == "__main__":
    L, C = learned(), classical()
    best = min(v[max(v)][0] for v in L.values() if v)
    lines = []
    for m in ORDER:
        if m not in L:
            continue
        v = L[m]
        c = fmt(v, m)
        top = v[max(v)]
        acc = rf"\textbf{{{c[0]}}}" if False else c[0]
        row = f"{NICE[m]} & " + " & ".join(c) + f" & {top[1]:.3f} \\\\"
        if abs(top[0] - best) < 1e-9:
            row = row.replace(c[-1], rf"\textbf{{{c[-1]}}}", 1)
        lines.append(row)
    lines.append(r"\hline")
    for lbl in (r"Gappy POD ($r{=}20$)", r"IDW ($k{=}8$)", "Nearest neighbor"):
        if lbl not in C:
            continue
        v = C[lbl]
        lines.append(f"{lbl} & " + " & ".join(fmt(v)) + f" & {v[max(v)][1]:.3f} \\\\")
    (OUT / "tab_surface_body.tex").write_text(
        "% GENERATED by src/figs_pof/make_surface_table.py -- do not hand-edit\n"
        + "\n".join(lines) + "\n")
    print((OUT / "tab_surface_body.tex").read_text())
